# IAPT: Benchmarking Small-Object Detection on Brain MRI: A Cerebral Microbleed Case Study

---
---

## Setup

The `Setup` phase prepares the environment for the pipeline.

- **Libraries**: Installs the necessary dependancies and imports all the libraries that will be used throughout the notebook. If you are running the notebook locally please read the `README.md` for instructions on how to install the libraries and setup the environment.

- **Logger Setup**: Setup the logger and ignore unnecessary nibabel warnings.

- **Google Drive Mounting**: Mounts Google Drive if its running in Colab, if not we set the `BASE_PATH` to the local data folder within our working directory.

- **Configuration Constants**: Defines all the necessary paths, file names and constants that will be used throughout the notebook.

- **Helper Functions**: Defines some helper functions used throughout the notebook.

**Why:** This is critical to ensure that all dependencies are met and that the notebook can adapt to both local and cloud (Google Colab) environments.

### Libraries

In [2]:
import sys
IS_COLAB = "google.colab" in sys.modules
if IS_COLAB: 
    from google.colab import drive
    !pip install nnunetv2==2.7.0 nibabel==5.4.2 tqdm scipy ipywidgets -q

# libraries
from pathlib import Path
from tqdm.auto import tqdm
import torch
import os
import logging
import subprocess
import numpy as np
import json
import nibabel as nib
from scipy.ndimage import label
import pandas as pd

### Logger Setup

In [3]:
############
# initilising and setting up the logger
logging.basicConfig(
    level=logging.INFO,
    format='%(levelname)s - %(message)s',
    force=True
)
nib.imageglobals.logger.setLevel(logging.WARNING)
logging.getLogger('nibabel').setLevel(logging.WARNING) # supressing warnings that are being fixed in the script
logger = logging.getLogger(__name__)

### Google Drive Mounting

May require adjustments to the `CLOUD_BASE_PATH` to access the folder that is stored on your specific Google Drive.

In [4]:
if IS_COLAB:
    DRIVE_PATH = Path("/content/drive")
    path_str = str(DRIVE_PATH)
    drive.mount(path_str, force_remount=True)
    logger.info(f"✅ Google Drive mounted to path '{path_str}'.")

    # adjust accordingly
    CLOUD_BASE_PATH = DRIVE_PATH / "MyDrive" / "iAPT_nnUNet-Matthias"
    BASE_PATH = CLOUD_BASE_PATH
else:
    BASE_PATH = Path.cwd().parent / "data"
    logger.info(f"✅ Running in local directory '{BASE_PATH}'.")

INFO - ✅ Running in local directory '/Users/matthiasmifsud/Desktop/AI/Year 2/SEM2/IAPT-Cerebral-Microbleeds/data'.

### Configuration Constants

In [5]:
############
# paths / files / constants

# paths
paths = {
    "nnUNet_raw": BASE_PATH / "nnUNet_raw",
    "nnUNet_preprocessed": BASE_PATH / "nnUNet_preprocessed",
    "nnUNet_results": BASE_PATH / "nnUNet_results"
}

DATASET_ID: str = "001"
DATASET_NAME: str = f"Dataset{DATASET_ID}_VALDO"
DATASET_PATH: Path = paths["nnUNet_raw"] / DATASET_NAME

IMAGES_PATH: Path = DATASET_PATH / "imagesTr"
LABELS_PATH: Path = DATASET_PATH / "labelsTr"
STATS_PATH: Path = DATASET_PATH / "verification_stats"
INFERENCE_OUTPUT_PATH = BASE_PATH / "nnUNet_inference"

ALL_PATHS = list(paths.values()) + [IMAGES_PATH, LABELS_PATH, STATS_PATH, INFERENCE_OUTPUT_PATH]

# files
METADATA_FILE: str = "dataset.json"
STATS_FILE: str = "stats.json"
INFER_EVAL_FILE: str = "evaluation_results.csv"

# constants
MODALITY_SUFFIXES: dict[str, str] = {
    "T1": "0000",
    "T2": "0001",
    "T2s": "0002"
}

DATA_TYPE: str = ".nii.gz"
SUB_PREFIX: str = "sub-"
DEVICE: str = "cuda" if IS_COLAB else "cpu"
K_FOLDS: int = 5

### Helper Functions

In [6]:
############
# directory creator helper function
def create_dirs(paths: list[Path] | Path, parents: bool = True, exist_ok: bool = True) -> None:
    if isinstance(paths, Path):
        paths = [paths]

    created = []

    for path in paths:
        if not path.exists():
            created.append(str(path))
        path.mkdir(parents=parents, exist_ok=exist_ok)

    if created:
        logger.info(f"✅ Created {len(created)} directorie(s): {', '.join(created)}")
    else:
        logger.info("✅  All directories already exist")

# file getter helper
def get_files(nib_path: str | Path) -> list:
    if nib_path == 'image':
        path = IMAGES_PATH
    elif nib_path == 'label':
        path = LABELS_PATH
    elif isinstance(nib_path, Path) and nib_path.exists():
        path = nib_path
    else:
        raise ValueError(f"'{nib_path}' is NOT a valid value for path_type.")

    files = list(path.glob(f"*{DATA_TYPE}"))

    if len(files) == 0:
        logger.error("❌ No label files found.")
        return []
    return files

def run_command(command):
    env = {**os.environ, "PYTHONUNBUFFERED": "1"}

    process = subprocess.Popen(
        command,
        shell=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        bufsize=1,
        env=env
    )

    for line in process.stdout:
        logger.info(line.rstrip())

    process.wait()
    return process.returncode

def is_not_empty(path):
    return path.exists() and any(path.iterdir())

---

## Setting Up Environment Variables

**What it does:**
- Dynamically creates the necessary directory tree.
- Sets the `nnUNet_raw`, `nnUNet_preprocessed`, and `nnUNet_results` variables in the system environment.

**Why:** Without these variables, the nnUNet tools cannot function, as they use these paths to organize the training and inference workflows.

In [7]:
# creating and logging all directories
create_dirs(ALL_PATHS)

# setting up envars for nnUNet
for key, path in paths.items():
    os.environ[key] = str(path)

logger.info("✅ Created all necessary directories and set nnUNet environment variables.")

INFO - ✅  All directories already exist
INFO - ✅ Created all necessary directories and set nnUNet environment variables.

---

## Affine Alignment, Dataset Conversion & Metadata Generation

**What it does:**
- **Standardization**: Converts the `original_dataset` to the nnUNet accepted format.

- **Affine Alignment**: Uses the T2* weighted image as a reference to align the label masks.

- **Metadata**: Generates `dataset.json`, defining modalities (T1, T2, T2*) and labels.

**Why:** Accurate alignment is critical for small-object detection; if the label mask is even slightly offset from the lesion in the MRI, the model will learn incorrect features. Also we need to convert the data to the nnUNet accepted format so that the commands can run flawlessly.

[!CAUTION] This section only runs if the notebook is being run locally, If its in colab then it means that the dataset has alredy been converted to nnUNet required format with the affine alignment and the generated metadata.

In [8]:
def valdo_to_nnu() -> int:
    logger.info("ℹ️ Converting Valdo Dataset and aligning labels to fit nnUNet format.")

    subjects = [f for f in ORIG_DATASET_PATH.iterdir() if f.is_dir() and f.name.startswith(SUB_PREFIX)] # 72 subjects

    sub_count = 0
    failed_sub = []

    for sub_dir in tqdm(subjects, desc="Saving Subjects", unit="subjects"): # iterating over all 72 subjects
        sub_id = sub_dir.name
        id = sub_id.replace(SUB_PREFIX, "")

        orig_filepaths = {
            "lbl": sub_dir / f"{sub_id}_space-T2S_CMB{DATA_TYPE}",
            "T1": sub_dir / f"{sub_id}_space-T2S_desc-masked_T1{DATA_TYPE}",
            "T2": sub_dir / f"{sub_id}_space-T2S_desc-masked_T2{DATA_TYPE}",
            "T2s": sub_dir / f"{sub_id}_space-T2S_desc-masked_T2S{DATA_TYPE}"
        }

        target_filepaths = {
            "lbl": LABELS_PATH / f"VALDO_{id}{DATA_TYPE}",
            "T1": IMAGES_PATH / f"VALDO_{id}_{MODALITY_SUFFIXES['T1']}{DATA_TYPE}",
            "T2": IMAGES_PATH / f"VALDO_{id}_{MODALITY_SUFFIXES['T2']}{DATA_TYPE}",
            "T2s": IMAGES_PATH / f"VALDO_{id}_{MODALITY_SUFFIXES['T2s']}{DATA_TYPE}"
        }

        # verifying that all 4 files exist else we have a failed subject
        if not all(file.exists() for file in orig_filepaths.values()):
            logger.warning(f"⚠️ Subject '{sub_id}' is incomplete. Missing one or more files.")
            failed_sub.append(sub_id)
            continue

        try:
            # saving all images to target
            for img_type in ["T1", "T2", "T2s"]:
                nib.save(nib.load(orig_filepaths[img_type]), target_filepaths[img_type])

            # aligning with the T2s only (since CMB are mainly detected with T2s weighting also segmentation was done on T2s)
            t2s_img = nib.load(orig_filepaths['T2s'])

            orig_lbl_img = nib.load(orig_filepaths['lbl'])

            aligned_lbl_img = nib.Nifti1Image(
                orig_lbl_img.get_fdata(),
                t2s_img.affine,
                t2s_img.header
            )
            nib.save(aligned_lbl_img, target_filepaths['lbl'])

            sub_count += 1
            logger.debug(f"Successfully converted and aligned '{sub_id}'.")

        except Exception as e:
            logger.error(f"❌ Error processing subject '{sub_id}': {e}")
            failed_sub.append(sub_id)

    if failed_sub:
        logger.error(f"❌ Failed to process the following subjects: {failed_sub}")

    return sub_count

def add_metadata(dataset_size) -> None:
    metadata = {
        "channel_names": {
            "0": "T1",
            "1": "T2",
            "2": "T2star"
        },
        "labels": {
            "background": 0,
            "microbleed": 1
        },
        "numTraining": dataset_size,
        "file_ending": DATA_TYPE
    }

    meta_path = DATASET_PATH / METADATA_FILE
    with open(meta_path, 'w') as f:
        json.dump(metadata, f, indent=4)
    logger.info(f"ℹ️ Added metadata to {str(meta_path)}.")

# running
if not IS_COLAB:
    ORIG_DATASET_PATH = BASE_PATH / "original_dataset" / "Task2"

    logger.info(f"ℹ️ Starting the nnUNet dataset setup...")
    # converting source data to target data
    dataset_size = valdo_to_nnu()
    # adding metadata
    add_metadata(dataset_size)
    logger.info("✅ Successfully finished setting up the nnUNet dataset.")
else:
    logger.info("✅ Dataset already converted to nnUNet format.")

INFO - ✅ Dataset already converted to nnUNet format.

---

## GPU Verification

**What it does:** Checks for NVIDIA GPU availability and tests CUDA functionality by running a small test tensor operation.

**Why:** Training on a CPU is not possible for this scale of data. Verifying the GPU at the start prevents the notebook from failing hours into a training process with a CPU.

In [9]:
# getting nvidia smi output
try:
    nvd_out = subprocess.check_output(["nvidia-smi"]).decode()
    logger.info(f"️️ℹ️ NVIDIA-SMI Output:\n{nvd_out}")
except Exception as e:
    logger.error(f"❌ nvidia-smi not available: {e}")
    if IS_COLAB:
        raise RuntimeError("GPU not available at runtime. (Fix: Runtime -> Change runtime type -> GPU)")

# check cuda
if torch.cuda.is_available():
    logger.info(f"️️✅ GPU Detected: {torch.cuda.get_device_name(0)}")

    # testing that the GPU is functional
    x = torch.rand(1000, 1000).cuda()
    logger.info(f"️️️️✅ GPU Functioning, tensor running on: {x.device}")
else:
    logger.error("❌ No CUDA GPUs detected.")
    if IS_COLAB:
        raise RuntimeError("GPU not available at runtime. (Fix: Runtime -> Change runtime type -> GPU)")
    else:
        logger.warning("⚠️ GPU not available at runtime, only CPU available.")

INFO - ️️ℹ️ NVIDIA-SMI Output:
Fri Apr 17 09:21:36 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA RTX PRO 6000 Blac...    Off |   00000000:05:00.0 Off |                    0 |
| N/A   30C    P0             47W /  600W |       0MiB /  97887MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

INFO - ️️✅ GPU Detected: NVIDIA RTX PRO 6000 Blackwell Server Edition
INFO - ️️️️✅ GPU Functioning, tensor running on: cuda:0

---

## Label Verification

**What it does:**
- **Integrity Check**: Ensures label values are binary (1/0).
- **Spatial Check**: Confirms that image dimensions and affine matrices match their corresponding labels.
- **Connected Components**: Calculates the count and volume of individual microbleeds for each subject.

**Why:** These verification steps ensure that the data is correct before we start the training and inference process. This prevents us passing misleading data to the model without knowing it and then having poor results without reason.

In [10]:
class LabelVerification:
    def __init__(self):
        self.corrupt_lbls = []
        self.misaligned_lbls = set()
        self.missing_mod = set()
        self.component_stats = {}

        try:
            with open(DATASET_PATH / METADATA_FILE, 'r') as file:
                data = json.load(file)
                self.dataset_size = data.get('numTraining', 0)
        except Exception as e:
            logger.error(f"❌ Failed to load {METADATA_FILE}: {e}")
            self.dataset_size = 0

    def _lbl_val_integrity(self, sub_id:str, lbl_data) -> bool:
        unique_vals = np.unique(lbl_data)
        if lbl_data.max() > 1 or lbl_data.min() < 0: # checking label mask range is between 0 and 1
            logger.error(f"❌ Label for '{sub_id}' is corrupt.")
            self.corrupt_lbls.append(sub_id)
            return False
        return True

    def _spatial_alignment(self, sub_id:str, lbl_img) -> None:
        for mod in MODALITY_SUFFIXES.values():
            img_path = IMAGES_PATH / f"{sub_id}_{mod}{DATA_TYPE}"

            if not img_path.exists():
                logger.error(f"❌ Missing Modality: '{sub_id}' is missing '{mod}'")
                self.missing_mod.add(f"{sub_id}_{mod}")
                continue

            img = nib.load(img_path)

            # dimension check
            if img.header.get_data_shape() != lbl_img.header.get_data_shape():
                logger.error(f"❌ Dimension Mismatch: '{sub_id}' ({mod})")
                self.misaligned_lbls.add(f"{sub_id}_{mod}")

            # spatial mapping check
            if not np.allclose(img.affine, lbl_img.affine, atol=1e-3):
                logger.error(f"❌ Affine Matrix Mismatch: '{sub_id}' ({mod})")
                self.misaligned_lbls.add(f"{sub_id}_{mod}")

    def _compute_connected_component(self, sub_id: str, lbl_img, lbl_data) -> None:
        # lbl_data == 1 is a microbleed
        label_mask, bleeds_count = label(lbl_data == 1)

        bleed_volumes = []
        voxel_spacing = ()

        # positive cases
        if bleeds_count > 0:
            # calc dimentions of bleed
            voxel_spacing = lbl_img.header.get_zooms()[:3] # ignoring 4th dim (time dim for fmri
            # get vol of each voxel
            voxel_vol = np.prod(voxel_spacing)

            # get size of each bleed (in voxel)
            bleed_sizes = np.bincount(label_mask.ravel())[1:] #skipping background dim (0s)
            # converting the bleed sizes to volumes
            bleed_volumes = (bleed_sizes * voxel_vol).tolist()

        self.component_stats[sub_id] = {
            'microbleed_count': int(bleeds_count),
            'microbleed_vol_mm3': [float(i) for i in bleed_volumes],
            'total_microbleed_vol_mm3': float(np.sum(bleed_volumes)),
            'voxel_spacing': tuple(float(i) for i in voxel_spacing),
            'max_bleed_vol_mm3': float(max(bleed_volumes)) if bleed_volumes else 0.0,
            'min_bleed_vol_mm3': float(min(bleed_volumes)) if bleed_volumes else 0.0,
        }

    def verify_labels(self) -> None:
        lbl_files = get_files('label')
        lbl_size = len(lbl_files)

        # fail if we cannot extract all of the labels
        if lbl_size != self.dataset_size:
            logger.error(f"❌ Extraced only {lbl_size}/{self.dataset_size} labels.")
            return

        logger.info(f"ℹ️ Starting label verification for {self.dataset_size} subjects...")
        for lbl_path in tqdm(lbl_files, desc="Verifying Subjects", unit="subjects"):
            sub_id = lbl_path.name.replace(DATA_TYPE, "")

            try:
                lbl_img = nib.load(lbl_path)
                lbl_data = np.asanyarray(lbl_img.dataobj)
            except Exception as e:
                logger.error(f"❌ Failed to load {sub_id}: {e}")
                self.corrupt_lbls.append(sub_id)
                continue

            # label val integrity
            if not self._lbl_val_integrity(sub_id, lbl_data):
                continue

            # spatial alignment
            self._spatial_alignment(sub_id, lbl_img)

            # connected component statistics
            self._compute_connected_component(sub_id, lbl_img, lbl_data)

        if not self.corrupt_lbls and not self.misaligned_lbls and not self.missing_mod:
            logger.info("✅ All checks passed succesfully")
            return
        logger.warning(f"⚠️ Issues found: {len(self.corrupt_lbls)} corrupt labels, {len(self.misaligned_lbls)} misaligned labels, {len(self.missing_mod)} missing modalities")

    def generate_summary(self) -> None:
        if not self.component_stats:
            logger.warning("⚠️ No statistics detected.")
            return

        stats = self.component_stats
        summary = {
            'total_subjects': len(stats),
            'statistics': stats
        }

        path = STATS_PATH / STATS_FILE
        create_dirs(STATS_PATH)
        with open(path, 'w') as f:
            json.dump(summary, f, indent=4)
        logger.info(f"ℹ️ Statistics saved to {path}")


verifier = LabelVerification()

stat_filepath = STATS_PATH / STATS_FILE
if not (stat_filepath).exists():
    logger.info("ℹ️ No existing stats found. Starting verification...")
    verifier.verify_labels()
    verifier.generate_summary()
else:
    try:
        with open(stat_filepath, 'r') as f:
            data = json.load(f)
            # checking if the stats file is valid
            if data.get('statistics'):
                logger.info(f"✅ Valid stats found for {data.get('total_subjects', 0)} subjects. Skipping.")
            else:
                raise ValueError("Stats file is empty of data.")
    # rerunning verification if the stats file is not valid
    except (json.JSONDecodeError, ValueError):
        logger.warning("⚠️ Stats file was corrupted or empty. Re-running verification...")
        verifier.verify_labels()
        verifier.generate_summary()

INFO - ✅ Valid stats found for 72 subjects. Skipping.

---

## Plan & Preprocessing

Executes the nnUNet's `nnUNetv2_plan_and_preprocess` command.

**What it does:**
- Extract a dataset fingerprint.
- Create one or more nnUNet configurations.
- Preprocess the data for those configurations.

The output is written into `nnUNet_preprocessed/DatasetXXX_Name`.

**Why:** This command analyses the dataset and generates a preprocessing plan. It computes target spacing, intensity normalisation statistics, patch sizes, and architecture configurations. It then preprocesses all 72 training cases. This perpares the data for the training stage.

[!CAUTION] This step is CPU-bound, not GPU-bound.

In [ ]:
preprocessed_path = paths["nnUNet_preprocessed"] / DATASET_NAME
if is_not_empty(preprocessed_path):
    logger.info("✅ Dataset already preprocessed. Skipping step.")
else:
    command = f"nnUNetv2_plan_and_preprocess -d {DATASET_ID} --verify_dataset_integrity"
    ret_code = run_command(command)

    if ret_code != 0:
        logger.error("❌ Preprocessing failed. Stopping pipeline.")
    else:
        logger.info("✅ Preprocessing completed successfully.")

INFO - Fingerprint extraction...
INFO - Dataset001_VALDO
INFO - Using <class 'nnunetv2.imageio.simpleitk_reader_writer.SimpleITKIO'> as reader/writer
INFO -
INFO - ####################
INFO - verify_dataset_integrity Done.
INFO - If you didn't see any error messages then your dataset is most likely OK!
INFO - ####################
INFO -
INFO - Using <class 'nnunetv2.imageio.simpleitk_reader_writer.SimpleITKIO'> as reader/writer
INFO -
INFO - Extracting dataset fingerprint:   0%|          | 0/72 [00:00<?, ?it/s]
INFO - Extracting dataset fingerprint:   1%|▏         | 1/72 [00:02<02:37,  2.21s/it]
INFO - Extracting dataset fingerprint:   7%|▋         | 5/72 [00:02<00:23,  2.85it/s]
INFO - Extracting dataset fingerprint:  12%|█▎        | 9/72 [00:02<00:12,  5.01it/s]
INFO - Extracting dataset fingerprint:  15%|█▌        | 11/72 [00:02<00:09,  6.35it/s]
INFO - Extracting dataset fingerprint:  18%|█▊        | 13/72 [00:03<00:16,  3.51it/s]
INFO - Extracting dataset fingerprint:  21%|██        | 15/72 [00:04<00:12,  4.62it/s]
INFO - Extracting dataset fingerprint:  24%|██▎       | 17/72 [00:04<00:09,  5.96it/s]
INFO - Extracting dataset fingerprint:  26%|██▋       | 19/72 [00:04<00:09,  5.64it/s]
INFO - Extracting dataset fingerprint:  29%|██▉       | 21/72 [00:05<00:13,  3.87it/s]
INFO - Extracting dataset fingerprint:  31%|███       | 22/72 [00:05<00:11,  4.33it/s]
INFO - Extracting dataset fingerprint:  32%|███▏      | 23/72 [00:05<00:11,  4.45it/s]
INFO - Extracting dataset fingerprint:  33%|███▎      | 24/72 [00:05<00:09,  5.07it/s]
INFO - Extracting dataset fingerprint:  36%|███▌      | 26/72 [00:06<00:09,  5.04it/s]
INFO - Extracting dataset fingerprint:  39%|███▉      | 28/72 [00:07<00:11,  3.70it/s]
INFO - Extracting dataset fingerprint:  40%|████      | 29/72 [00:07<00:10,  4.23it/s]
INFO - Extracting dataset fingerprint:  42%|████▏     | 30/72 [00:07<00:08,  4.86it/s]
INFO - Extracting dataset fingerprint:  43%|████▎     | 31/72 [00:07<00:07,  5.55it/s]
INFO - Extracting dataset fingerprint:  44%|████▍     | 32/72 [00:07<00:07,  5.39it/s]
INFO - Extracting dataset fingerprint:  47%|████▋     | 34/72 [00:07<00:06,  5.86it/s]
INFO - Extracting dataset fingerprint:  49%|████▊     | 35/72 [00:07<00:05,  6.49it/s]
INFO - Extracting dataset fingerprint:  50%|█████     | 36/72 [00:08<00:10,  3.44it/s]
INFO - Extracting dataset fingerprint:  53%|█████▎    | 38/72 [00:08<00:06,  5.25it/s]
INFO - Extracting dataset fingerprint:  56%|█████▌    | 40/72 [00:08<00:05,  6.38it/s]
INFO - Extracting dataset fingerprint:  58%|█████▊    | 42/72 [00:09<00:04,  6.46it/s]
INFO - Extracting dataset fingerprint:  62%|██████▎   | 45/72 [00:09<00:03,  8.53it/s]
INFO - Extracting dataset fingerprint:  65%|██████▌   | 47/72 [00:09<00:02, 10.22it/s]
INFO - Extracting dataset fingerprint:  71%|███████   | 51/72 [00:09<00:01, 13.10it/s]
INFO - Extracting dataset fingerprint:  74%|███████▎  | 53/72 [00:09<00:01, 14.30it/s]
INFO - Extracting dataset fingerprint:  79%|███████▉  | 57/72 [00:09<00:00, 19.42it/s]
INFO - Extracting dataset fingerprint:  83%|████████▎ | 60/72 [00:10<00:00, 21.70it/s]
INFO - Extracting dataset fingerprint:  88%|████████▊ | 63/72 [00:10<00:00, 19.07it/s]
INFO - Extracting dataset fingerprint:  92%|█████████▏| 66/72 [00:10<00:00, 21.37it/s]
INFO - Extracting dataset fingerprint:  96%|█████████▌| 69/72 [00:10<00:00, 23.39it/s]
INFO - Extracting dataset fingerprint: 100%|██████████| 72/72 [00:10<00:00,  6.83it/s]
INFO - Experiment planning...
INFO -
INFO - ############################
INFO - INFO: You are using the old nnU-Net default planner. We have updated our recommendations. Please consider using those instead! Read more here: https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/resenc_presets.md
INFO - ############################
INFO -
INFO - Attempting to find 3d_lowres config.
INFO - Current spacing: [0.82400001 0.50292944 0.50292944].
INFO - Current patch size: (np.int64(96), np.int64(192), np.int64(128)).
INFO - Current median shape: [186.40776699 379.61165049 309.70873786]
INFO - Attempting to find 3d_lowres config.
INFO - Current spacing: [0.84872001 0.51801733 0.51801733].
INFO - Current patch size: (np.int64(96), np.int64(192), np.int64(128)).
INFO - Current median shape: [180.97841455 368.55500047 300.68809501]
INFO - Attempting to find 3d_lowres config.
INFO - Current spacing: [0.87418161 0.53355784 0.53355784].
INFO - Current patch size: (np.int64(96), np.int64(192), np.int64(128)).
INFO - Current median shape: [175.7071986  357.82038881 291.93018933]
INFO - Attempting to find 3d_lowres config.
INFO - Current spacing: [0.90040706 0.54956458 0.54956458].
INFO - Current patch size: (np.int64(96), np.int64(192), np.int64(128)).
INFO - Current median shape: [170.5895132  347.39843574 283.42736829]
INFO - Attempting to find 3d_lowres config.
INFO - Current spacing: [0.92741927 0.56605152 0.56605152].
INFO - Current patch size: (np.int64(96), np.int64(192), np.int64(128)).
INFO - Current median shape: [165.6208866  337.28003469 275.17220222]
INFO - Attempting to find 3d_lowres config.
INFO - Current spacing: [0.95524185 0.58303306 0.58303306].
INFO - Current patch size: (np.int64(96), np.int64(192), np.int64(128)).
INFO - Current median shape: [160.79697728 327.45634436 267.15747788]
INFO - Attempting to find 3d_lowres config.
INFO - Current spacing: [0.98389911 0.60052406 0.60052406].
INFO - Current patch size: (np.int64(96), np.int64(192), np.int64(128)).
INFO - Current median shape: [156.11357018 317.91878094 259.37619212]
INFO - Attempting to find 3d_lowres config.
INFO - Current spacing: [1.01341608 0.61853978 0.61853978].
INFO - Current patch size: (np.int64(96), np.int64(192), np.int64(128)).
INFO - Current median shape: [151.56657299 308.65901062 251.82154575]
INFO - Attempting to find 3d_lowres config.
INFO - Current spacing: [1.04381856 0.63709597 0.63709597].
INFO - Current patch size: (np.int64(96), np.int64(192), np.int64(128)).
INFO - Current median shape: [147.15201261 299.66894235 244.48693762]
INFO - Attempting to find 3d_lowres config.
INFO - Current spacing: [1.07513312 0.65620885 0.65620885].
INFO - Current patch size: (np.int64(96), np.int64(192), np.int64(128)).
INFO - Current median shape: [142.86603166 290.94072072 237.36595885]
INFO - Attempting to find 3d_lowres config.
INFO - Current spacing: [1.10738711 0.67589511 0.67589511].
INFO - Current patch size: (np.int64(96), np.int64(192), np.int64(128)).
INFO - Current median shape: [138.70488511 282.46671915 230.45238724]
INFO - 2D U-Net configuration:
INFO - {'data_identifier': 'nnUNetPlans_2d', 'preprocessor_name': 'DefaultPreprocessor', 'batch_size': 23, 'patch_size': (np.int64(448), np.int64(320)), 'median_image_size_in_voxels': array([391., 319.]), 'spacing': array([0.48828101, 0.48828101]), 'normalization_schemes': ['ZScoreNormalization', 'ZScoreNormalization', 'ZScoreNormalization'], 'use_mask_for_norm': [True, True, True], 'resampling_fn_data': 'resample_data_or_seg_to_shape', 'resampling_fn_seg': 'resample_data_or_seg_to_shape', 'resampling_fn_data_kwargs': {'is_seg': False, 'order': 3, 'order_z': 0, 'force_separate_z': None}, 'resampling_fn_seg_kwargs': {'is_seg': True, 'order': 1, 'order_z': 0, 'force_separate_z': None}, 'resampling_fn_probabilities': 'resample_data_or_seg_to_shape', 'resampling_fn_probabilities_kwargs': {'is_seg': False, 'order': 1, 'order_z': 0, 'force_separate_z': None}, 'architecture': {'network_class_name': 'dynamic_network_architectures.architectures.unet.PlainConvUNet', 'arch_kwargs': {'n_stages': 7, 'features_per_stage': (32, 64, 128, 256, 512, 512, 512), 'conv_op': 'torch.nn.modules.conv.Conv2d', 'kernel_sizes': ((3, 3), (3, 3), (3, 3), (3, 3), (3, 3), (3, 3), (3, 3)), 'strides': ((1, 1), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2)), 'n_conv_per_stage': (2, 2, 2, 2, 2, 2, 2), 'n_conv_per_stage_decoder': (2, 2, 2, 2, 2, 2), 'conv_bias': True, 'norm_op': 'torch.nn.modules.instancenorm.InstanceNorm2d', 'norm_op_kwargs': {'eps': 1e-05, 'affine': True}, 'dropout_op': None, 'dropout_op_kwargs': None, 'nonlin': 'torch.nn.LeakyReLU', 'nonlin_kwargs': {'inplace': True}}, '_kw_requires_import': ('conv_op', 'norm_op', 'dropout_op', 'nonlin')}, 'batch_dice': True}
INFO -
INFO - Using <class 'nnunetv2.imageio.simpleitk_reader_writer.SimpleITKIO'> as reader/writer
INFO - 3D lowres U-Net configuration:
INFO - {'data_identifier': 'nnUNetPlans_3d_lowres', 'preprocessor_name': 'DefaultPreprocessor', 'batch_size': 2, 'patch_size': (np.int64(96), np.int64(192), np.int64(128)), 'median_image_size_in_voxels': (139, 282, 230), 'spacing': array([1.10738711, 0.67589511, 0.67589511]), 'normalization_schemes': ['ZScoreNormalization', 'ZScoreNormalization', 'ZScoreNormalization'], 'use_mask_for_norm': [True, True, True], 'resampling_fn_data': 'resample_data_or_seg_to_shape', 'resampling_fn_seg': 'resample_data_or_seg_to_shape', 'resampling_fn_data_kwargs': {'is_seg': False, 'order': 3, 'order_z': 0, 'force_separate_z': None}, 'resampling_fn_seg_kwargs': {'is_seg': True, 'order': 1, 'order_z': 0, 'force_separate_z': None}, 'resampling_fn_probabilities': 'resample_data_or_seg_to_shape', 'resampling_fn_probabilities_kwargs': {'is_seg': False, 'order': 1, 'order_z': 0, 'force_separate_z': None}, 'architecture': {'network_class_name': 'dynamic_network_architectures.architectures.unet.PlainConvUNet', 'arch_kwargs': {'n_stages': 6, 'features_per_stage': (32, 64, 128, 256, 320, 320), 'conv_op': 'torch.nn.modules.conv.Conv3d', 'kernel_sizes': ((3, 3, 3), (3, 3, 3), (3, 3, 3), (3, 3, 3), (3, 3, 3), (3, 3, 3)), 'strides': ((1, 1, 1), (2, 2, 2), (2, 2, 2), (2, 2, 2), (2, 2, 2), (1, 2, 2)), 'n_conv_per_stage': (2, 2, 2, 2, 2, 2), 'n_conv_per_stage_decoder': (2, 2, 2, 2, 2), 'conv_bias': True, 'norm_op': 'torch.nn.modules.instancenorm.InstanceNorm3d', 'norm_op_kwargs': {'eps': 1e-05, 'affine': True}, 'dropout_op': None, 'dropout_op_kwargs': None, 'nonlin': 'torch.nn.LeakyReLU', 'nonlin_kwargs': {'inplace': True}}, '_kw_requires_import': ('conv_op', 'norm_op', 'dropout_op', 'nonlin')}, 'batch_dice': False, 'next_stage': '3d_cascade_fullres'}
INFO -
INFO - 3D fullres U-Net configuration:
INFO - {'data_identifier': 'nnUNetPlans_3d_fullres', 'preprocessor_name': 'DefaultPreprocessor', 'batch_size': 2, 'patch_size': (np.int64(96), np.int64(192), np.int64(128)), 'median_image_size_in_voxels': array([192., 391., 319.]), 'spacing': array([0.80000001, 0.48828101, 0.48828101]), 'normalization_schemes': ['ZScoreNormalization', 'ZScoreNormalization', 'ZScoreNormalization'], 'use_mask_for_norm': [True, True, True], 'resampling_fn_data': 'resample_data_or_seg_to_shape', 'resampling_fn_seg': 'resample_data_or_seg_to_shape', 'resampling_fn_data_kwargs': {'is_seg': False, 'order': 3, 'order_z': 0, 'force_separate_z': None}, 'resampling_fn_seg_kwargs': {'is_seg': True, 'order': 1, 'order_z': 0, 'force_separate_z': None}, 'resampling_fn_probabilities': 'resample_data_or_seg_to_shape', 'resampling_fn_probabilities_kwargs': {'is_seg': False, 'order': 1, 'order_z': 0, 'force_separate_z': None}, 'architecture': {'network_class_name': 'dynamic_network_architectures.architectures.unet.PlainConvUNet', 'arch_kwargs': {'n_stages': 6, 'features_per_stage': (32, 64, 128, 256, 320, 320), 'conv_op': 'torch.nn.modules.conv.Conv3d', 'kernel_sizes': ((3, 3, 3), (3, 3, 3), (3, 3, 3), (3, 3, 3), (3, 3, 3), (3, 3, 3)), 'strides': ((1, 1, 1), (2, 2, 2), (2, 2, 2), (2, 2, 2), (2, 2, 2), (1, 2, 2)), 'n_conv_per_stage': (2, 2, 2, 2, 2, 2), 'n_conv_per_stage_decoder': (2, 2, 2, 2, 2), 'conv_bias': True, 'norm_op': 'torch.nn.modules.instancenorm.InstanceNorm3d', 'norm_op_kwargs': {'eps': 1e-05, 'affine': True}, 'dropout_op': None, 'dropout_op_kwargs': None, 'nonlin': 'torch.nn.LeakyReLU', 'nonlin_kwargs': {'inplace': True}}, '_kw_requires_import': ('conv_op', 'norm_op', 'dropout_op', 'nonlin')}, 'batch_dice': True}
INFO -
INFO - Plans were saved to /content/drive/MyDrive/iAPT_nnUNet-Matthias/nnUNet_preprocessed/Dataset001_VALDO/nnUNetPlans.json
INFO - Preprocessing...
INFO - Preprocessing dataset Dataset001_VALDO
INFO - Configuration: 2d...
INFO - {'data_identifier': 'nnUNetPlans_2d', 'preprocessor_name': 'DefaultPreprocessor', 'batch_size': 23, 'patch_size': [448, 320], 'median_image_size_in_voxels': [391.0, 319.0], 'spacing': [0.4882810115814209, 0.4882810115814209], 'normalization_schemes': ['ZScoreNormalization', 'ZScoreNormalization', 'ZScoreNormalization'], 'use_mask_for_norm': [True, True, True], 'resampling_fn_data': 'resample_data_or_seg_to_shape', 'resampling_fn_seg': 'resample_data_or_seg_to_shape', 'resampling_fn_data_kwargs': {'is_seg': False, 'order': 3, 'order_z': 0, 'force_separate_z': None}, 'resampling_fn_seg_kwargs': {'is_seg': True, 'order': 1, 'order_z': 0, 'force_separate_z': None}, 'resampling_fn_probabilities': 'resample_data_or_seg_to_shape', 'resampling_fn_probabilities_kwargs': {'is_seg': False, 'order': 1, 'order_z': 0, 'force_separate_z': None}, 'architecture': {'network_class_name': 'dynamic_network_architectures.architectures.unet.PlainConvUNet', 'arch_kwargs': {'n_stages': 7, 'features_per_stage': [32, 64, 128, 256, 512, 512, 512], 'conv_op': 'torch.nn.modules.conv.Conv2d', 'kernel_sizes': [[3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3]], 'strides': [[1, 1], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2]], 'n_conv_per_stage': [2, 2, 2, 2, 2, 2, 2], 'n_conv_per_stage_decoder': [2, 2, 2, 2, 2, 2], 'conv_bias': True, 'norm_op': 'torch.nn.modules.instancenorm.InstanceNorm2d', 'norm_op_kwargs': {'eps': 1e-05, 'affine': True}, 'dropout_op': None, 'dropout_op_kwargs': None, 'nonlin': 'torch.nn.LeakyReLU', 'nonlin_kwargs': {'inplace': True}}, '_kw_requires_import': ['conv_op', 'norm_op', 'dropout_op', 'nonlin']}, 'batch_dice': True}
INFO -
INFO - Preprocessing cases:   0%|          | 0/72 [00:00<?, ?it/s]
INFO - Preprocessing cases:   1%|▏         | 1/72 [00:05<06:53,  5.82s/it]
INFO - Preprocessing cases:   4%|▍         | 3/72 [00:05<01:46,  1.55s/it]
INFO - Preprocessing cases:   7%|▋         | 5/72 [00:07<01:11,  1.06s/it]
INFO - Preprocessing cases:   8%|▊         | 6/72 [00:07<00:52,  1.25it/s]
INFO - Preprocessing cases:  10%|▉         | 7/72 [00:07<00:41,  1.57it/s]
INFO - Preprocessing cases:  12%|█▎        | 9/72 [00:08<00:41,  1.51it/s]
INFO - Preprocessing cases:  14%|█▍        | 10/72 [00:09<00:38,  1.60it/s]
INFO - Preprocessing cases:  15%|█▌        | 11/72 [00:09<00:29,  2.04it/s]
INFO - Preprocessing cases:  17%|█▋        | 12/72 [01:03<14:53, 14.89s/it]
INFO - Preprocessing cases:  18%|█▊        | 13/72 [01:04<10:45, 10.94s/it]
INFO - Preprocessing cases:  19%|█▉        | 14/72 [01:05<08:01,  8.30s/it]
INFO - Preprocessing cases:  21%|██        | 15/72 [01:06<05:40,  5.97s/it]
INFO - Preprocessing cases:  24%|██▎       | 17/72 [01:06<03:02,  3.32s/it]
INFO - Preprocessing cases:  25%|██▌       | 18/72 [01:08<02:37,  2.92s/it]
INFO - Preprocessing cases:  26%|██▋       | 19/72 [01:08<01:56,  2.19s/it]
INFO - Preprocessing cases:  28%|██▊       | 20/72 [01:58<13:14, 15.28s/it]
INFO - Preprocessing cases:  29%|██▉       | 21/72 [02:01<09:58, 11.73s/it]
INFO - Preprocessing cases:  31%|███       | 22/72 [02:03<07:22,  8.85s/it]
INFO - Preprocessing cases:  32%|███▏      | 23/72 [02:03<05:21,  6.55s/it]
INFO - Preprocessing cases:  33%|███▎      | 24/72 [02:04<03:46,  4.73s/it]
INFO - Preprocessing cases:  36%|███▌      | 26/72 [02:04<02:00,  2.62s/it]
INFO - Preprocessing cases:  38%|███▊      | 27/72 [02:04<01:34,  2.10s/it]
INFO - Preprocessing cases:  39%|███▉      | 28/72 [02:52<10:15, 13.99s/it]
INFO - Preprocessing cases:  40%|████      | 29/72 [02:58<08:28, 11.83s/it]
INFO - Preprocessing cases:  42%|████▏     | 30/72 [03:00<06:13,  8.90s/it]
INFO - Preprocessing cases:  43%|████▎     | 31/72 [03:00<04:24,  6.45s/it]
INFO - Preprocessing cases:  44%|████▍     | 32/72 [03:01<03:19,  4.99s/it]
INFO - Preprocessing cases:  46%|████▌     | 33/72 [03:02<02:20,  3.59s/it]
INFO - Preprocessing cases:  47%|████▋     | 34/72 [03:02<01:38,  2.59s/it]
INFO - Preprocessing cases:  49%|████▊     | 35/72 [03:02<01:14,  2.00s/it]
INFO - Preprocessing cases:  50%|█████     | 36/72 [03:47<08:44, 14.56s/it]
INFO - Preprocessing cases:  51%|█████▏    | 37/72 [03:52<06:54, 11.83s/it]
INFO - Preprocessing cases:  53%|█████▎    | 38/72 [03:54<05:01,  8.86s/it]
INFO - Preprocessing cases:  54%|█████▍    | 39/72 [03:56<03:40,  6.69s/it]
INFO - Preprocessing cases:  56%|█████▌    | 40/72 [03:58<02:55,  5.50s/it]
INFO - Preprocessing cases:  57%|█████▋    | 41/72 [03:58<02:00,  3.88s/it]
INFO - Preprocessing cases:  58%|█████▊    | 42/72 [03:59<01:24,  2.81s/it]
INFO - Preprocessing cases:  60%|█████▉    | 43/72 [03:59<01:01,  2.12s/it]
INFO - Preprocessing cases:  61%|██████    | 44/72 [04:02<01:02,  2.23s/it]
INFO - Preprocessing cases:  62%|██████▎   | 45/72 [04:03<00:54,  2.01s/it]
INFO - Preprocessing cases:  64%|██████▍   | 46/72 [04:05<00:49,  1.89s/it]
INFO - Preprocessing cases:  65%|██████▌   | 47/72 [04:06<00:41,  1.65s/it]
INFO - Preprocessing cases:  67%|██████▋   | 48/72 [04:06<00:32,  1.34s/it]
INFO - Preprocessing cases:  68%|██████▊   | 49/72 [04:08<00:30,  1.33s/it]
INFO - Preprocessing cases:  69%|██████▉   | 50/72 [04:09<00:31,  1.41s/it]
INFO - Preprocessing cases:  71%|███████   | 51/72 [04:11<00:30,  1.44s/it]
INFO - Preprocessing cases:  72%|███████▏  | 52/72 [04:12<00:27,  1.40s/it]
INFO - Preprocessing cases:  74%|███████▎  | 53/72 [04:13<00:20,  1.10s/it]
INFO - Preprocessing cases:  75%|███████▌  | 54/72 [04:13<00:18,  1.01s/it]
INFO - Preprocessing cases:  76%|███████▋  | 55/72 [04:14<00:16,  1.06it/s]
INFO - Preprocessing cases:  78%|███████▊  | 56/72 [04:16<00:17,  1.08s/it]
INFO - Preprocessing cases:  79%|███████▉  | 57/72 [04:17<00:19,  1.33s/it]
INFO - Preprocessing cases:  81%|████████  | 58/72 [04:19<00:18,  1.35s/it]
INFO - Preprocessing cases:  82%|████████▏ | 59/72 [04:19<00:14,  1.10s/it]
INFO - Preprocessing cases:  83%|████████▎ | 60/72 [04:21<00:15,  1.31s/it]
INFO - Preprocessing cases:  85%|████████▍ | 61/72 [04:22<00:14,  1.28s/it]
INFO - Preprocessing cases:  86%|████████▌ | 62/72 [04:23<00:11,  1.13s/it]
INFO - Preprocessing cases:  88%|████████▊ | 63/72 [04:25<00:12,  1.36s/it]
INFO - Preprocessing cases:  89%|████████▉ | 64/72 [04:27<00:11,  1.40s/it]
INFO - Preprocessing cases:  90%|█████████ | 65/72 [04:27<00:08,  1.25s/it]
INFO - Preprocessing cases:  92%|█████████▏| 66/72 [04:32<00:12,  2.14s/it]
INFO - Preprocessing cases:  93%|█████████▎| 67/72 [04:33<00:08,  1.80s/it]
INFO - Preprocessing cases:  94%|█████████▍| 68/72 [04:33<00:05,  1.29s/it]
INFO - Preprocessing cases:  96%|█████████▌| 69/72 [04:34<00:03,  1.32s/it]
INFO - Preprocessing cases:  97%|█████████▋| 70/72 [04:35<00:02,  1.20s/it]
INFO - Preprocessing cases:  99%|█████████▊| 71/72 [04:37<00:01,  1.35s/it]
INFO - Preprocessing cases: 100%|██████████| 72/72 [04:38<00:00,  1.36s/it]
INFO - Preprocessing cases: 100%|██████████| 72/72 [04:38<00:00,  3.87s/it]
INFO - Configuration: 3d_fullres...

---

## Training

Starts training using the `nnUNetv2_train` for the `2d` configuration across all 5 folds.

**What it does:**
- Calls the `nnUNetv2_train` command for the `2d` configuration across all 5 folds.
- Has checkpointing implemented across each fold hence if the training gets interrupted you just rerun the cell and then training completes where it left off.

**Why:** The training section builds the weights for our detection model so that we can then run inference to evaluate how it performs with CMB detection. The implementation of checkpointing helps save alot of time since training is a long process and an interruption across a fold could waste hours. With checkpointing we could just re-run the cell and we would not lose any data or time as it completes where it left off.

[!CAUTION] This section requires a GPU.

In [11]:
def get_epoch_from_checkpoint(checkpoint_path):
    try:
        checkpoint = torch.load(checkpoint_path, map_location='cpu', weights_only=False)
        return checkpoint.get('current_epoch', checkpoint.get('epoch', "Unknown"))
    except Exception as e:
        logger.warning(f"⚠️ Could not read checkpoint: {e}")
        return "Unknown"

# runner
models_path = paths["nnUNet_results"] / DATASET_NAME / "nnUNetTrainer__nnUNetPlans__2d"
for fold in range(0, K_FOLDS):
    fold_dir = models_path / f"fold_{fold}"
    final_cp = fold_dir / "checkpoint_final.pth"
    best_cp = fold_dir / "checkpoint_best.pth"
    latest_cp = fold_dir / "checkpoint_latest.pth"

    if final_cp.exists():
        logger.info(f"✅ Fold {fold} is COMPLETED.")
        continue

    existing_cp = None
    if latest_cp.exists():
        existing_cp = latest_cp
    elif best_cp.exists():
        existing_cp = best_cp

    if existing_cp:
        epoch = get_epoch_from_checkpoint(existing_cp)
        logger.info(f"ℹ️ Resuming Fold {fold} from Epoch {epoch}...")
        checkpoint_flag = "--c"
    else:
        logger.info(f"ℹ️ Starting Fold {fold} from the beginning (Epoch 0)...")
        checkpoint_flag = ""

    command = f"nnUNetv2_train {DATASET_ID} 2d {fold} {checkpoint_flag} --npz -device {DEVICE}".strip()
    ret_code = run_command(command)


    if ret_code != 0:
        logger.error(f"❌ Training crashed on Fold {fold}. Stopping pipeline.")
        break
    else:
        logger.info(f"✅ Fold {fold} completed successfully.")

INFO - ✅ Fold 0 is COMPLETED.
INFO - ✅ Fold 1 is COMPLETED.
INFO - ✅ Fold 2 is COMPLETED.
INFO - ✅ Fold 3 is COMPLETED.
INFO - ✅ Fold 4 is COMPLETED.

---

## Inference

**What it does:**
- Uses the `nnUNetv2_predict` command to generate segmentation masks for the test subjects.
- Applies the ensemble of weights learned during the 5-fold cross-validation to produce the most stable prediction.
- Saves the resulting predictions as NIfTI files in the `nnUNet_inference` directory.

**Why:** With inference we can now test the trained model and from this we can evaluate its performance to see if the trained model is actually good at detecting CMB.

[!CAUTION] This section requires a GPU.

In [12]:
command = (
    f"nnUNetv2_predict "
    f"-i {str(IMAGES_PATH)} "
    f"-o {str(INFERENCE_OUTPUT_PATH)} "
    f"-d {DATASET_ID} "
    f"-c 2d "
    f"-f 0 1 2 3 4 "
    f"--save_probabilities"
)

if is_not_empty(INFERENCE_OUTPUT_PATH):
    logger.info("✅ Inference already done. Skipping this part.")
else:
    logger.info("ℹ️ Starting inference...")

    ret_code = run_command(command)#removed logger since run_command function already has access to logger internally

    if ret_code != 0:
        logger.error("❌ Inference failed.")

Streaming output truncated to the last 5000 lines.
INFO -  44%|████▍     | 504/1152 [00:03<00:04, 136.39it/s]
INFO -  45%|████▍     | 518/1152 [00:03<00:04, 136.39it/s]
INFO -  46%|████▌     | 532/1152 [00:03<00:04, 136.45it/s]
INFO -  47%|████▋     | 546/1152 [00:04<00:04, 136.58it/s]
INFO -  49%|████▊     | 560/1152 [00:04<00:04, 136.50it/s]
INFO -  50%|████▉     | 574/1152 [00:04<00:04, 136.36it/s]
INFO -  51%|█████     | 588/1152 [00:04<00:04, 136.44it/s]
INFO -  52%|█████▏    | 602/1152 [00:04<00:04, 136.52it/s]
INFO -  53%|█████▎    | 616/1152 [00:04<00:03, 136.56it/s]
INFO -  55%|█████▍    | 630/1152 [00:04<00:03, 136.58it/s]
INFO -  56%|█████▌    | 644/1152 [00:04<00:03, 136.62it/s]
INFO -  57%|█████▋    | 658/1152 [00:04<00:03, 136.50it/s]
INFO -  58%|█████▊    | 672/1152 [00:04<00:03, 136.56it/s]
INFO -  60%|█████▉    | 686/1152 [00:05<00:03, 136.64it/s]
INFO -  61%|██████    | 700/1152 [00:05<00:03, 136.66it/s]
INFO -  62%|██████▏   | 714/1152 [00:05<00:03, 136.70it/s]
INFO -  63%|██████▎   | 728/1152 [00:05<00:03, 136.52it/s]
INFO -  64%|██████▍   | 742/1152 [00:05<00:03, 136.36it/s]
INFO -  66%|██████▌   | 756/1152 [00:05<00:02, 136.27it/s]
INFO -  67%|██████▋   | 770/1152 [00:05<00:02, 136.27it/s]
INFO -  68%|██████▊   | 784/1152 [00:05<00:02, 136.32it/s]
INFO -  69%|██████▉   | 798/1152 [00:05<00:02, 136.22it/s]
INFO -  70%|███████   | 812/1152 [00:05<00:02, 136.25it/s]
INFO -  72%|███████▏  | 826/1152 [00:06<00:02, 136.33it/s]
INFO -  73%|███████▎  | 840/1152 [00:06<00:02, 136.54it/s]
INFO -  74%|███████▍  | 854/1152 [00:06<00:02, 136.48it/s]
INFO -  75%|███████▌  | 868/1152 [00:06<00:02, 136.55it/s]
INFO -  77%|███████▋  | 882/1152 [00:06<00:01, 136.46it/s]
INFO -  78%|███████▊  | 896/1152 [00:06<00:01, 136.41it/s]
INFO -  79%|███████▉  | 910/1152 [00:06<00:01, 136.39it/s]
INFO -  80%|████████  | 924/1152 [00:06<00:01, 136.14it/s]
INFO -  81%|████████▏ | 938/1152 [00:06<00:01, 135.95it/s]
INFO -  83%|████████▎ | 952/1152 [00:06<00:01, 136.16it/s]
INFO -  84%|████████▍ | 966/1152 [00:07<00:01, 136.33it/s]
INFO -  85%|████████▌ | 980/1152 [00:07<00:01, 136.27it/s]
INFO -  86%|████████▋ | 994/1152 [00:07<00:01, 136.26it/s]
INFO -  88%|████████▊ | 1008/1152 [00:07<00:01, 136.32it/s]
INFO -  89%|████████▊ | 1022/1152 [00:07<00:00, 136.52it/s]
INFO -  90%|████████▉ | 1036/1152 [00:07<00:00, 136.66it/s]
INFO -  91%|█████████ | 1050/1152 [00:07<00:00, 136.79it/s]
INFO -  92%|█████████▏| 1064/1152 [00:07<00:00, 136.86it/s]
INFO -  94%|█████████▎| 1078/1152 [00:07<00:00, 136.86it/s]
INFO -  95%|█████████▍| 1092/1152 [00:08<00:00, 136.83it/s]
INFO -  96%|█████████▌| 1106/1152 [00:08<00:00, 136.82it/s]
INFO -  97%|█████████▋| 1120/1152 [00:08<00:00, 136.70it/s]
INFO -  98%|█████████▊| 1134/1152 [00:08<00:00, 136.64it/s]
INFO - 100%|█████████▉| 1148/1152 [00:08<00:00, 136.65it/s]
INFO - 100%|██████████| 1152/1152 [00:08<00:00, 136.40it/s]
INFO -
INFO -   0%|          | 0/1152 [00:00<?, ?it/s]
INFO -   1%|          | 14/1152 [00:00<00:08, 135.28it/s]
INFO -   2%|▏         | 28/1152 [00:00<00:08, 137.47it/s]
INFO -   4%|▎         | 42/1152 [00:00<00:08, 138.23it/s]
INFO -   5%|▍         | 56/1152 [00:00<00:07, 138.75it/s]
INFO -   6%|▌         | 70/1152 [00:00<00:07, 138.12it/s]
INFO -   7%|▋         | 84/1152 [00:00<00:07, 137.70it/s]
INFO -   9%|▊         | 98/1152 [00:00<00:07, 137.43it/s]
INFO -  10%|▉         | 112/1152 [00:00<00:07, 137.26it/s]
INFO -  11%|█         | 126/1152 [00:00<00:07, 137.19it/s]
INFO -  12%|█▏        | 140/1152 [00:01<00:07, 137.11it/s]
INFO -  13%|█▎        | 154/1152 [00:01<00:07, 137.06it/s]
INFO -  15%|█▍        | 168/1152 [00:01<00:07, 137.03it/s]
INFO -  16%|█▌        | 182/1152 [00:01<00:07, 137.01it/s]
INFO -  17%|█▋        | 196/1152 [00:01<00:06, 136.98it/s]
INFO -  18%|█▊        | 210/1152 [00:01<00:06, 136.98it/s]
INFO -  19%|█▉        | 224/1152 [00:01<00:06, 136.86it/s]
INFO -  21%|██        | 238/1152 [00:01<00:06, 136.51it/s]
INFO -  22%|██▏       | 252/1152 [00:01<00:06, 136.38it/s]
INFO -  23%|██▎       | 266/1152 [00:01<00:06, 136.23it/s]
INFO -  24%|██▍       | 280/1152 [00:02<00:06, 136.22it/s]
INFO -  26%|██▌       | 294/1152 [00:02<00:06, 136.37it/s]
INFO -  27%|██▋       | 308/1152 [00:02<00:06, 136.19it/s]
INFO -  28%|██▊       | 322/1152 [00:02<00:06, 136.10it/s]
INFO -  29%|██▉       | 336/1152 [00:02<00:06, 136.00it/s]
INFO -  30%|███       | 350/1152 [00:02<00:05, 136.05it/s]
INFO -  32%|███▏      | 364/1152 [00:02<00:05, 136.20it/s]
INFO -  33%|███▎      | 378/1152 [00:02<00:05, 136.14it/s]
INFO -  34%|███▍      | 392/1152 [00:02<00:05, 136.24it/s]
INFO -  35%|███▌      | 406/1152 [00:02<00:05, 136.26it/s]
INFO -  36%|███▋      | 420/1152 [00:03<00:05, 136.36it/s]
INFO -  38%|███▊      | 434/1152 [00:03<00:05, 136.29it/s]
INFO -  39%|███▉      | 448/1152 [00:03<00:05, 136.29it/s]
INFO -  40%|████      | 462/1152 [00:03<00:05, 136.21it/s]
INFO -  41%|████▏     | 476/1152 [00:03<00:04, 136.19it/s]
INFO -  43%|████▎     | 490/1152 [00:03<00:04, 136.12it/s]
INFO -  44%|████▍     | 504/1152 [00:03<00:04, 136.06it/s]
INFO -  45%|████▍     | 518/1152 [00:03<00:04, 136.12it/s]
INFO -  46%|████▌     | 532/1152 [00:03<00:04, 136.02it/s]
INFO -  47%|████▋     | 546/1152 [00:03<00:04, 136.16it/s]
INFO -  49%|████▊     | 560/1152 [00:04<00:04, 136.38it/s]
INFO -  50%|████▉     | 574/1152 [00:04<00:04, 136.65it/s]
INFO -  51%|█████     | 588/1152 [00:04<00:04, 136.71it/s]
INFO -  52%|█████▏    | 602/1152 [00:04<00:04, 136.83it/s]
INFO -  53%|█████▎    | 616/1152 [00:04<00:03, 136.78it/s]
INFO -  55%|█████▍    | 630/1152 [00:04<00:03, 136.69it/s]
INFO -  56%|█████▌    | 644/1152 [00:04<00:03, 136.63it/s]
INFO -  57%|█████▋    | 658/1152 [00:04<00:03, 136.57it/s]
INFO -  58%|█████▊    | 672/1152 [00:04<00:03, 136.43it/s]
INFO -  60%|█████▉    | 686/1152 [00:05<00:03, 136.41it/s]
INFO -  61%|██████    | 700/1152 [00:05<00:03, 136.37it/s]
INFO -  62%|██████▏   | 714/1152 [00:05<00:03, 136.47it/s]
INFO -  63%|██████▎   | 728/1152 [00:05<00:03, 136.56it/s]
INFO -  64%|██████▍   | 742/1152 [00:05<00:03, 136.53it/s]
INFO -  66%|██████▌   | 756/1152 [00:05<00:02, 136.52it/s]
INFO -  67%|██████▋   | 770/1152 [00:05<00:02, 136.42it/s]
INFO -  68%|██████▊   | 784/1152 [00:05<00:02, 136.26it/s]
INFO -  69%|██████▉   | 798/1152 [00:05<00:02, 136.11it/s]
INFO -  70%|███████   | 812/1152 [00:05<00:02, 136.13it/s]
INFO -  72%|███████▏  | 826/1152 [00:06<00:02, 136.08it/s]
INFO -  73%|███████▎  | 840/1152 [00:06<00:02, 136.12it/s]
INFO -  74%|███████▍  | 854/1152 [00:06<00:02, 136.22it/s]
INFO -  75%|███████▌  | 868/1152 [00:06<00:02, 136.14it/s]
INFO -  77%|███████▋  | 882/1152 [00:06<00:01, 136.20it/s]
INFO -  78%|███████▊  | 896/1152 [00:06<00:01, 136.26it/s]
INFO -  79%|███████▉  | 910/1152 [00:06<00:01, 136.24it/s]
INFO -  80%|████████  | 924/1152 [00:06<00:01, 136.16it/s]
INFO -  81%|████████▏ | 938/1152 [00:06<00:01, 136.11it/s]
INFO -  83%|████████▎ | 952/1152 [00:06<00:01, 136.04it/s]
INFO -  84%|████████▍ | 966/1152 [00:07<00:01, 136.10it/s]
INFO -  85%|████████▌ | 980/1152 [00:07<00:01, 136.20it/s]
INFO -  86%|████████▋ | 994/1152 [00:07<00:01, 136.28it/s]
INFO -  88%|████████▊ | 1008/1152 [00:07<00:01, 136.33it/s]
INFO -  89%|████████▊ | 1022/1152 [00:07<00:00, 136.29it/s]
INFO -  90%|████████▉ | 1036/1152 [00:07<00:00, 136.22it/s]
INFO -  91%|█████████ | 1050/1152 [00:07<00:00, 136.25it/s]
INFO -  92%|█████████▏| 1064/1152 [00:07<00:00, 136.19it/s]
INFO -  94%|█████████▎| 1078/1152 [00:07<00:00, 136.13it/s]
INFO -  95%|█████████▍| 1092/1152 [00:08<00:00, 136.19it/s]
INFO -  96%|█████████▌| 1106/1152 [00:08<00:00, 136.25it/s]
INFO -  97%|█████████▋| 1120/1152 [00:08<00:00, 136.40it/s]
INFO -  98%|█████████▊| 1134/1152 [00:08<00:00, 136.33it/s]
INFO - 100%|█████████▉| 1148/1152 [00:08<00:00, 136.45it/s]
INFO - 100%|██████████| 1152/1152 [00:08<00:00, 136.46it/s]
INFO -
INFO -   0%|          | 0/1152 [00:00<?, ?it/s]
INFO -   1%|          | 14/1152 [00:00<00:08, 134.76it/s]
INFO -   2%|▏         | 28/1152 [00:00<00:08, 136.59it/s]
INFO -   4%|▎         | 42/1152 [00:00<00:08, 137.45it/s]
INFO -   5%|▍         | 56/1152 [00:00<00:07, 138.04it/s]
INFO -   6%|▌         | 70/1152 [00:00<00:07, 138.25it/s]
INFO -   7%|▋         | 84/1152 [00:00<00:07, 138.18it/s]
INFO -   9%|▊         | 98/1152 [00:00<00:07, 137.80it/s]
INFO -  10%|▉         | 112/1152 [00:00<00:07, 137.51it/s]
INFO -  11%|█         | 126/1152 [00:00<00:07, 137.34it/s]
INFO -  12%|█▏        | 140/1152 [00:01<00:07, 137.21it/s]
INFO -  13%|█▎        | 154/1152 [00:01<00:07, 136.94it/s]
INFO -  15%|█▍        | 168/1152 [00:01<00:07, 136.56it/s]
INFO -  16%|█▌        | 182/1152 [00:01<00:07, 136.41it/s]
INFO -  17%|█▋        | 196/1152 [00:01<00:07, 136.26it/s]
INFO -  18%|█▊        | 210/1152 [00:01<00:06, 136.20it/s]
INFO -  19%|█▉        | 224/1152 [00:01<00:06, 136.16it/s]
INFO -  21%|██        | 238/1152 [00:01<00:06, 136.16it/s]
INFO -  22%|██▏       | 252/1152 [00:01<00:06, 136.19it/s]
INFO -  23%|██▎       | 266/1152 [00:01<00:06, 136.16it/s]
INFO -  24%|██▍       | 280/1152 [00:02<00:06, 136.13it/s]
INFO -  26%|██▌       | 294/1152 [00:02<00:06, 136.17it/s]
INFO -  27%|██▋       | 308/1152 [00:02<00:06, 136.07it/s]
INFO -  28%|██▊       | 322/1152 [00:02<00:06, 136.05it/s]
INFO -  29%|██▉       | 336/1152 [00:02<00:05, 136.04it/s]
INFO -  30%|███       | 350/1152 [00:02<00:05, 135.91it/s]
INFO -  32%|███▏      | 364/1152 [00:02<00:05, 135.84it/s]
INFO -  33%|███▎      | 378/1152 [00:02<00:05, 135.80it/s]
INFO -  34%|███▍      | 392/1152 [00:02<00:05, 135.73it/s]
INFO -  35%|███▌      | 406/1152 [00:02<00:05, 135.69it/s]
INFO -  36%|███▋      | 420/1152 [00:03<00:05, 135.51it/s]
INFO -  38%|███▊      | 434/1152 [00:03<00:05, 135.61it/s]
INFO -  39%|███▉      | 448/1152 [00:03<00:05, 135.70it/s]
INFO -  40%|████      | 462/1152 [00:03<00:05, 135.82it/s]
INFO -  41%|████▏     | 476/1152 [00:03<00:04, 135.88it/s]
INFO -  43%|████▎     | 490/1152 [00:03<00:04, 135.97it/s]
INFO -  44%|████▍     | 504/1152 [00:03<00:04, 135.92it/s]
INFO -  45%|████▍     | 518/1152 [00:03<00:04, 135.99it/s]
INFO -  46%|████▌     | 532/1152 [00:03<00:04, 135.90it/s]
INFO -  47%|████▋     | 546/1152 [00:04<00:04, 135.97it/s]
INFO -  49%|████▊     | 560/1152 [00:04<00:04, 135.82it/s]
INFO -  50%|████▉     | 574/1152 [00:04<00:04, 135.72it/s]
INFO -  51%|█████     | 588/1152 [00:04<00:04, 135.67it/s]
INFO -  52%|█████▏    | 602/1152 [00:04<00:04, 135.61it/s]
INFO -  53%|█████▎    | 616/1152 [00:04<00:03, 135.66it/s]
INFO -  55%|█████▍    | 630/1152 [00:04<00:03, 135.65it/s]
INFO -  56%|█████▌    | 644/1152 [00:04<00:03, 135.62it/s]
INFO -  57%|█████▋    | 658/1152 [00:04<00:03, 135.51it/s]
INFO -  58%|█████▊    | 672/1152 [00:04<00:03, 135.48it/s]
INFO -  60%|█████▉    | 686/1152 [00:05<00:03, 135.65it/s]
INFO -  61%|██████    | 700/1152 [00:05<00:03, 135.63it/s]
INFO -  62%|██████▏   | 714/1152 [00:05<00:03, 135.70it/s]
INFO -  63%|██████▎   | 728/1152 [00:05<00:03, 135.75it/s]
INFO -  64%|██████▍   | 742/1152 [00:05<00:03, 135.72it/s]
INFO -  66%|██████▌   | 756/1152 [00:05<00:02, 135.72it/s]
INFO -  67%|██████▋   | 770/1152 [00:05<00:02, 135.78it/s]
INFO -  68%|██████▊   | 784/1152 [00:05<00:02, 135.75it/s]
INFO -  69%|██████▉   | 798/1152 [00:05<00:02, 135.85it/s]
INFO -  70%|███████   | 812/1152 [00:05<00:02, 135.96it/s]
INFO -  72%|███████▏  | 826/1152 [00:06<00:02, 135.82it/s]
INFO -  73%|███████▎  | 840/1152 [00:06<00:02, 135.72it/s]
INFO -  74%|███████▍  | 854/1152 [00:06<00:02, 135.75it/s]
INFO -  75%|███████▌  | 868/1152 [00:06<00:02, 135.82it/s]
INFO -  77%|███████▋  | 882/1152 [00:06<00:01, 135.89it/s]
INFO -  78%|███████▊  | 896/1152 [00:06<00:01, 136.02it/s]
INFO -  79%|███████▉  | 910/1152 [00:06<00:01, 136.10it/s]
INFO -  80%|████████  | 924/1152 [00:06<00:01, 136.14it/s]
INFO -  81%|████████▏ | 938/1152 [00:06<00:01, 136.15it/s]
INFO -  83%|████████▎ | 952/1152 [00:06<00:01, 136.13it/s]
INFO -  84%|████████▍ | 966/1152 [00:07<00:01, 136.08it/s]
INFO -  85%|████████▌ | 980/1152 [00:07<00:01, 136.14it/s]
INFO -  86%|████████▋ | 994/1152 [00:07<00:01, 136.05it/s]
INFO -  88%|████████▊ | 1008/1152 [00:07<00:01, 136.11it/s]
INFO -  89%|████████▊ | 1022/1152 [00:07<00:00, 135.99it/s]
INFO -  90%|████████▉ | 1036/1152 [00:07<00:00, 136.04it/s]
INFO -  91%|█████████ | 1050/1152 [00:07<00:00, 136.07it/s]
INFO -  92%|█████████▏| 1064/1152 [00:07<00:00, 136.03it/s]
INFO -  94%|█████████▎| 1078/1152 [00:07<00:00, 136.05it/s]
INFO -  95%|█████████▍| 1092/1152 [00:08<00:00, 136.14it/s]
INFO -  96%|█████████▌| 1106/1152 [00:08<00:00, 136.19it/s]
INFO -  97%|█████████▋| 1120/1152 [00:08<00:00, 136.04it/s]
INFO -  98%|█████████▊| 1134/1152 [00:08<00:00, 136.05it/s]
INFO - 100%|█████████▉| 1148/1152 [00:08<00:00, 136.06it/s]
INFO - 100%|██████████| 1152/1152 [00:08<00:00, 136.09it/s]
INFO -
INFO -   0%|          | 0/1152 [00:00<?, ?it/s]
INFO -   1%|          | 14/1152 [00:00<00:08, 135.09it/s]
INFO -   2%|▏         | 28/1152 [00:00<00:08, 137.55it/s]
INFO -   4%|▎         | 42/1152 [00:00<00:08, 138.41it/s]
INFO -   5%|▍         | 56/1152 [00:00<00:07, 138.52it/s]
INFO -   6%|▌         | 70/1152 [00:00<00:07, 137.96it/s]
INFO -   7%|▋         | 84/1152 [00:00<00:07, 137.28it/s]
INFO -   9%|▊         | 98/1152 [00:00<00:07, 137.00it/s]
INFO -  10%|▉         | 112/1152 [00:00<00:07, 136.77it/s]
INFO -  11%|█         | 126/1152 [00:00<00:07, 136.65it/s]
INFO -  12%|█▏        | 140/1152 [00:01<00:07, 136.41it/s]
INFO -  13%|█▎        | 154/1152 [00:01<00:07, 136.28it/s]
INFO -  15%|█▍        | 168/1152 [00:01<00:07, 136.26it/s]
INFO -  16%|█▌        | 182/1152 [00:01<00:07, 136.30it/s]
INFO -  17%|█▋        | 196/1152 [00:01<00:07, 136.31it/s]
INFO -  18%|█▊        | 210/1152 [00:01<00:06, 136.40it/s]
INFO -  19%|█▉        | 224/1152 [00:01<00:06, 136.30it/s]
INFO -  21%|██        | 238/1152 [00:01<00:06, 136.07it/s]
INFO -  22%|██▏       | 252/1152 [00:01<00:06, 136.16it/s]
INFO -  23%|██▎       | 266/1152 [00:01<00:06, 136.25it/s]
INFO -  24%|██▍       | 280/1152 [00:02<00:06, 136.37it/s]
INFO -  26%|██▌       | 294/1152 [00:02<00:06, 136.35it/s]
INFO -  27%|██▋       | 308/1152 [00:02<00:06, 136.27it/s]
INFO -  28%|██▊       | 322/1152 [00:02<00:06, 136.44it/s]
INFO -  29%|██▉       | 336/1152 [00:02<00:05, 136.58it/s]
INFO -  30%|███       | 350/1152 [00:02<00:05, 136.60it/s]
INFO -  32%|███▏      | 364/1152 [00:02<00:05, 136.75it/s]
INFO -  33%|███▎      | 378/1152 [00:02<00:05, 136.81it/s]
INFO -  34%|███▍      | 392/1152 [00:02<00:05, 136.72it/s]
INFO -  35%|███▌      | 406/1152 [00:02<00:05, 136.76it/s]
INFO -  36%|███▋      | 420/1152 [00:03<00:05, 136.76it/s]
INFO -  38%|███▊      | 434/1152 [00:03<00:05, 136.80it/s]
INFO -  39%|███▉      | 448/1152 [00:03<00:05, 136.81it/s]
INFO -  40%|████      | 462/1152 [00:03<00:05, 136.80it/s]
INFO -  41%|████▏     | 476/1152 [00:03<00:04, 136.79it/s]
INFO -  43%|████▎     | 490/1152 [00:03<00:04, 136.58it/s]
INFO -  44%|████▍     | 504/1152 [00:03<00:04, 136.29it/s]
INFO -  45%|████▍     | 518/1152 [00:03<00:04, 136.17it/s]
INFO -  46%|████▌     | 532/1152 [00:03<00:04, 136.18it/s]
INFO -  47%|████▋     | 546/1152 [00:03<00:04, 136.17it/s]
INFO -  49%|████▊     | 560/1152 [00:04<00:04, 136.14it/s]
INFO -  50%|████▉     | 574/1152 [00:04<00:04, 136.08it/s]
INFO -  51%|█████     | 588/1152 [00:04<00:04, 136.13it/s]
INFO -  52%|█████▏    | 602/1152 [00:04<00:04, 136.18it/s]
INFO -  53%|█████▎    | 616/1152 [00:04<00:03, 136.08it/s]
INFO -  55%|█████▍    | 630/1152 [00:04<00:03, 136.01it/s]
INFO -  56%|█████▌    | 644/1152 [00:04<00:03, 135.98it/s]
INFO -  57%|█████▋    | 658/1152 [00:04<00:03, 135.96it/s]
INFO -  58%|█████▊    | 672/1152 [00:04<00:03, 135.95it/s]
INFO -  60%|█████▉    | 686/1152 [00:05<00:03, 135.95it/s]
INFO -  61%|██████    | 700/1152 [00:05<00:03, 135.86it/s]
INFO -  62%|██████▏   | 714/1152 [00:05<00:03, 135.92it/s]
INFO -  63%|██████▎   | 728/1152 [00:05<00:03, 135.86it/s]
INFO -  64%|██████▍   | 742/1152 [00:05<00:03, 135.73it/s]
INFO -  66%|██████▌   | 756/1152 [00:05<00:02, 135.66it/s]
INFO -  67%|██████▋   | 770/1152 [00:05<00:02, 135.63it/s]
INFO -  68%|██████▊   | 784/1152 [00:05<00:02, 135.72it/s]
INFO -  69%|██████▉   | 798/1152 [00:05<00:02, 136.86it/s]
INFO -  70%|███████   | 812/1152 [00:05<00:02, 137.76it/s]
INFO -  72%|███████▏  | 826/1152 [00:06<00:02, 138.11it/s]
INFO -  73%|███████▎  | 840/1152 [00:06<00:02, 137.73it/s]
INFO -  74%|███████▍  | 854/1152 [00:06<00:02, 137.48it/s]
INFO -  75%|███████▌  | 868/1152 [00:06<00:02, 137.26it/s]
INFO -  77%|███████▋  | 882/1152 [00:06<00:01, 137.13it/s]
INFO -  78%|███████▊  | 896/1152 [00:06<00:01, 137.04it/s]
INFO -  79%|███████▉  | 910/1152 [00:06<00:01, 136.98it/s]
INFO -  80%|████████  | 924/1152 [00:06<00:01, 136.93it/s]
INFO -  81%|████████▏ | 938/1152 [00:06<00:01, 136.93it/s]
INFO -  83%|████████▎ | 952/1152 [00:06<00:01, 136.90it/s]
INFO -  84%|████████▍ | 966/1152 [00:07<00:01, 136.89it/s]
INFO -  85%|████████▌ | 980/1152 [00:07<00:01, 136.89it/s]
INFO -  86%|████████▋ | 994/1152 [00:07<00:01, 136.91it/s]
INFO -  88%|████████▊ | 1008/1152 [00:07<00:01, 136.92it/s]
INFO -  89%|████████▊ | 1022/1152 [00:07<00:00, 136.91it/s]
INFO -  90%|████████▉ | 1036/1152 [00:07<00:00, 136.91it/s]
INFO -  91%|█████████ | 1050/1152 [00:07<00:00, 136.94it/s]
INFO -  92%|█████████▏| 1064/1152 [00:07<00:00, 136.95it/s]
INFO -  94%|█████████▎| 1078/1152 [00:07<00:00, 136.99it/s]
INFO -  95%|█████████▍| 1092/1152 [00:07<00:00, 137.01it/s]
INFO -  96%|█████████▌| 1106/1152 [00:08<00:00, 137.07it/s]
INFO -  97%|█████████▋| 1120/1152 [00:08<00:00, 137.05it/s]
INFO -  98%|█████████▊| 1134/1152 [00:08<00:00, 137.04it/s]
INFO - 100%|█████████▉| 1148/1152 [00:08<00:00, 137.03it/s]
INFO - 100%|██████████| 1152/1152 [00:08<00:00, 136.64it/s]
INFO - sending off prediction to background worker for resampling and export
INFO - done with VALDO_225
INFO -
INFO - Predicting VALDO_226:
INFO - perform_everything_on_device: True
INFO -
INFO -   0%|          | 0/1152 [00:00<?, ?it/s]
INFO -   1%|          | 14/1152 [00:00<00:08, 132.98it/s]
INFO -   2%|▏         | 28/1152 [00:00<00:08, 134.20it/s]
INFO -   4%|▎         | 42/1152 [00:00<00:08, 134.69it/s]
INFO -   5%|▍         | 56/1152 [00:00<00:08, 133.50it/s]
INFO -   6%|▌         | 70/1152 [00:00<00:08, 134.13it/s]
INFO -   7%|▋         | 84/1152 [00:00<00:07, 134.62it/s]
INFO -   9%|▊         | 98/1152 [00:00<00:07, 135.19it/s]
INFO -  10%|▉         | 112/1152 [00:00<00:07, 135.53it/s]
INFO -  11%|█         | 126/1152 [00:00<00:07, 135.60it/s]
INFO -  12%|█▏        | 140/1152 [00:01<00:07, 135.43it/s]
INFO -  13%|█▎        | 154/1152 [00:01<00:07, 135.36it/s]
INFO -  15%|█▍        | 168/1152 [00:01<00:07, 135.63it/s]
INFO -  16%|█▌        | 182/1152 [00:01<00:07, 135.68it/s]
INFO -  17%|█▋        | 196/1152 [00:01<00:07, 135.76it/s]
INFO -  18%|█▊        | 210/1152 [00:01<00:06, 135.80it/s]
INFO -  19%|█▉        | 224/1152 [00:01<00:06, 135.77it/s]
INFO -  21%|██        | 238/1152 [00:01<00:06, 135.80it/s]
INFO -  22%|██▏       | 252/1152 [00:01<00:06, 135.69it/s]
INFO -  23%|██▎       | 266/1152 [00:01<00:06, 135.61it/s]
INFO -  24%|██▍       | 280/1152 [00:02<00:06, 135.64it/s]
INFO -  26%|██▌       | 294/1152 [00:02<00:06, 135.71it/s]
INFO -  27%|██▋       | 308/1152 [00:02<00:06, 135.70it/s]
INFO -  28%|██▊       | 322/1152 [00:02<00:06, 135.63it/s]
INFO -  29%|██▉       | 336/1152 [00:02<00:06, 135.31it/s]
INFO -  30%|███       | 350/1152 [00:02<00:05, 134.93it/s]
INFO -  32%|███▏      | 364/1152 [00:02<00:05, 134.95it/s]
INFO -  33%|███▎      | 378/1152 [00:02<00:05, 134.98it/s]
INFO -  34%|███▍      | 392/1152 [00:02<00:05, 135.41it/s]
INFO -  35%|███▌      | 406/1152 [00:02<00:05, 136.57it/s]
INFO -  37%|███▋      | 421/1152 [00:03<00:05, 137.68it/s]
INFO -  38%|███▊      | 435/1152 [00:03<00:05, 137.57it/s]
INFO -  39%|███▉      | 449/1152 [00:03<00:05, 137.36it/s]
INFO -  40%|████      | 463/1152 [00:03<00:05, 137.22it/s]

---

## Evaluation

**What it does:**
- **Metric Calculation**: Computes the Lesion-Level Sensitivity (Recall), False Positives, Lesion-Level F1-Score and Voxel Dice Coefficient.

- **Exporting**: Exports results into a CSV file `evaluation_results.csv` to identify the model performance across each subject.

**Why:** This determines the performance of the trained model for each subject and we could go to conclusions on whether or not the model is working as expected.

In [8]:
def evaluate_subject(gt_lbl_path: Path):
    true_filename = gt_lbl_path.name
    pred_lbl_path = INFERENCE_OUTPUT_PATH / true_filename
    sub_id = true_filename.replace(DATA_TYPE, "")

    if not pred_lbl_path.exists():
        logger.warning(f"⚠️ No prediction label found for subject '{sub_id}'.")
        return {
            "subject_id": sub_id,
            "sensitivity": None,
            "false_positives": None,
            "f1_score": None,
            "dice": None,
            "num_gt_microbleeds": None,
            "num_pred_microbleeds": None
        }

    # 3d connectivity
    structure = np.ones((3, 3, 3), dtype=np.uint8)

    gt_lbl_img = nib.load(gt_lbl_path)
    pred_lbl_img = nib.load(pred_lbl_path)
    
    gt_data = (gt_lbl_img.get_fdata() > 0) # array test data label mask
    pred_data = (pred_lbl_img.get_fdata() > 0) # array prediction label mask
    
    if not np.allclose(gt_lbl_img.affine, pred_lbl_img.affine):
        logger.warning(f"⚠️ Affine mismatch for subject {sub_id}")

    # connected components extraction
    gt_labeled, gt_num = label(gt_data, structure=structure)
    pred_labeled, pred_num = label(pred_data, structure=structure)

    # lesion level sensitivity (recall)
    overlap_true_lbl = np.unique(gt_labeled[pred_data])
    overlap_true_lbl = overlap_true_lbl[overlap_true_lbl > 0] # including only the microbleeds (no background)

    detected_true_count = len(overlap_true_lbl) # good predictions
    ll_sens = detected_true_count / gt_num if gt_num > 0 else 1.0 # recall

    # false positive calc
    overlap_pred_lbl = np.unique(pred_labeled[gt_data])
    overlap_pred_lbl = overlap_pred_lbl[overlap_pred_lbl > 0] # including only the microbleeds (no background)

    detected_pred_count = len(overlap_pred_lbl) # good predictions
    fp = pred_num - detected_pred_count

    # precision
    if pred_num == 0:
        ll_prec = 1.0 if gt_num == 0 else 0.0
    else:
        ll_prec = detected_pred_count / pred_num

    # lesion level f1-score
    if (ll_prec + ll_sens) > 0:
        ll_f1 = (2 * ll_prec * ll_sens) / (ll_prec + ll_sens)
    else:
        ll_f1 = 0.0

    # perfect negative case
    if gt_num == 0 and pred_num == 0:
        ll_f1 = 1.0

    # voxel calc
    intersection = np.logical_and(gt_data, pred_data).sum()
    gt_sum = gt_data.sum()
    pred_sum = pred_data.sum()

    if gt_sum == 0 and pred_sum == 0:
        vox_dice = 1.0
    else:
        vox_dice = (2.0 * intersection) / (gt_sum + pred_sum + 1e-6)


    return {
        "subject_id": sub_id,
        "sensitivity": ll_sens,
        "false_positives": fp,
        "f1_score": ll_f1,
        "dice": vox_dice,
        "num_gt_microbleeds": gt_num,
        "num_pred_microbleeds": pred_num
    }

def calc_and_save_eval():
    true_labels = get_files('label')

    eval_results = []
    for true_lbl in true_labels:
        result = evaluate_subject(true_lbl)
        if result is not None:
            eval_results.append(result)

    df = pd.DataFrame(eval_results)
    path = INFERENCE_OUTPUT_PATH / INFER_EVAL_FILE
    df.to_csv(path, index=False)
    logger.info(f"✅ Inference evaluation complete. Saved to {path}")
    return df

df = calc_and_save_eval()
display(df.head())
display(df.describe())

INFO - ✅ Inference evaluation complete. Saved to /Users/matthiasmifsud/Desktop/AI/Year 2/SEM2/IAPT-Cerebral-Microbleeds/data/nnUNet_inference/evaluation_results.csv

,subject_id,sensitivity,false_positives,f1_score,dice,num_gt_microbleeds,num_pred_microbleeds
0,VALDO_224,1.000,0,1.000000,1.000000,0,0
1,VALDO_324,1.000,0,1.000000,1.000000,1,1
2,VALDO_228,0.875,0,0.933333,0.849758,8,7
3,VALDO_212,1.000,0,1.000000,0.875000,1,1
4,VALDO_312,0.500,0,0.666667,0.800000,2,1

,sensitivity,false_positives,f1_score,dice,num_gt_microbleeds,num_pred_microbleeds
count,72.000000,72.0,72.000000,72.000000,72.000000,72.000000
mean,0.960042,0.0,0.970842,0.895497,3.277778,3.319444
std,0.140773,0.0,0.126630,0.159776,9.464868,10.027886
min,0.000000,0.0,0.000000,0.000000,0.000000,0.000000
25%,1.000000,0.0,1.000000,0.830152,0.000000,0.000000
50%,1.000000,0.0,1.000000,0.977396,1.000000,1.000000
75%,1.000000,0.0,1.000000,1.000000,2.000000,2.000000
max,1.000000,0.0,1.000000,1.000000,73.000000,79.000000

##
---
---